server:
  port: 8082

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: DEPARTMENT-SERVICE
    zipkin:
      base-url: http://127.0.0.1:9411/zipkin/
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


